# fly.toml app configuration file generated for have-i-been-faned on 2025-07-02T20:27:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'have-i-been-faned'
primary_region = 'ams'

[build]
dockerfile = './DockerfileAPI'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 2
processes = ['app']

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 1
